#!/usr/bin/env bash

set -e
set -x

export FC=gfortran-6

if [ -z "$WORKDIR" ]; then
    export WORKDIR=$HOME/workdir
    mkdir -p $WORKDIR
fi

if [ -z "$INSTALLDIR" ]; then
    export INSTALLDIR=$HOME/installdir
    mkdir -p $INSTALLDIR
fi

function install_szip {
    echo install_szip
    cd $WORKDIR
    wget --no-check-certificate -q http://www.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz
    tar -xzf szip-2.1.1.tar.gz
    cd szip-2.1.1
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export CPPFLAGS="$CPPFLAGS -I${INSTALLDIR}/include"
    export LDFLAGS="$LDFLAGS -L${INSTALLDIR}/lib"
}

function install_hdf5 {
    echo install_hdf5
    cd $WORKDIR
    wget --no-check-certificate -q https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.gz
    tar -xzf hdf5-1.10.5.tar.gz
    cd hdf5-1.10.5
    ./configure --prefix=$INSTALLDIR &> config.log
    (make | awk 'NR%100 == 0')
    make install
    export LIBDIR=${INSTALLDIR}/lib
}

function install_netcdf_c {
    echo install_netcdf_c
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-c-4.7.3.tar.gz
    tar -xzf netcdf-c-4.7.3.tar.gz
    cd netcdf-c-4.7.3
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export LD_LIBRARY_PATH=${INSTALLDIR}/lib
}

function install_netcdf_fortran {
    echo install_netcdf_fortran
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.5.2.tar.gz
    tar -xzf netcdf-fortran-4.5.2.tar.gz
    cd netcdf-fortran-4.5.2
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
}

function icar_before_install {
    echo icar_before_install

    # Install szip (used by hdf5)
    install_szip
    # Install HDF5
    install_hdf5
    # Install NetCDF-C
    install_netcdf_c
    # Install NetCDF fortran
    install_netcdf_fortran

    # put installed bin directory in PATH
    export PATH=${INSTALLDIR}/bin:$PATH
}

function icar_install {
    echo icar_install
    cd ${TRAVIS_BUILD_DIR}

    export FC=gfortran-6
    export NETCDF=${INSTALLDIR}
    export FFTW=/usr

    make -C src clean; make -C src -j4 test
    # test serial build
    make -C src clean; make -C src MODE=debugslow
    # test parallel builds with different compile settings
    make -C src clean; make -C src -j4 MODE=debugslow
    make -C src clean; make -C src -j4 MODE=debug
    make -C src clean; make -C src -j4 MODE=debugompslow
    make -C src clean; make -C src -j4 MODE=debugomp
    make -C src clean; make -C src -j4 MODE=profile
    make -C src clean; make -C src -j4 MODE=fast
    make -C src clean; make -C src -j4
    echo "icar install succeeded"
}

function icar_script {

    cd ./src
    # ./icar --version
    # ./icar -h
    ./icar
    for i in *_test; do
        ./${i}
    done
    cd ../
    echo "icar script succeeded"
}

function icar_after_success {
  echo icar_after_success
  echo "icar build succeeded"
}

function icar_after_failure {
  echo icar_after_failure
  echo "icar build failed"
}
