#!/usr/bin/env bash

set -e
set -x

export FC=gfortran-6
export FFTW=/usr
export NETCDF=/usr

if [ -z "$WORKDIR" ]; then
    export WORKDIR=$HOME/workdir
    mkdir -p $WORKDIR
fi

if [ -z "$INSTALLDIR" ]; then
    export INSTALLDIR=$HOME/installdir
    mkdir -p $INSTALLDIR
fi

function install_szip {
    echo install_szip
    cd $WORKDIR
    wget --no-check-certificate -q http://www.hdfgroup.org/ftp/lib-external/szip/2.1/src/szip-2.1.tar.gz
    tar -xzf szip-2.1.tar.gz
    cd szip-2.1
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export CPPFLAGS="$CPPFLAGS -I${INSTALLDIR}/include"
    export LDFLAGS="$LDFLAGS -L${INSTALLDIR}/lib"
}

function install_hdf5 {
    echo install_hdf5
    cd $WORKDIR
    wget --no-check-certificate -q https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.1.tar.gz
    tar -xzf hdf5-1.10.1.tar.gz
    cd hdf5-1.10.1
    ./configure --prefix=$INSTALLDIR &> config.log
    (make | awk 'NR%100 == 0')
    make install
    export LIBDIR=${INSTALLDIR}/lib
}

function install_netcdf_c {
    echo install_netcdf_c
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.tar.gz
    tar -xzf netcdf-4.4.1.tar.gz
    cd netcdf-4.4.1
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export LD_LIBRARY_PATH=${INSTALLDIR}/lib
}

function install_netcdf_fortran {
    echo install_netcdf_fortran
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz
    tar -xzf netcdf-fortran-4.4.4.tar.gz
    cd netcdf-fortran-4.4.4
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
}

function icar_before_install {
    echo icar_before_install
    ls -l /usr/lib/
    ls -l /usr/local/lib/
    ls -l /usr/
    ls -l /usr/local
    /usr/bin/gfortran-6 --version
    gfortran-6 --version
    # Install szip (used by hdf5)
    install_szip
    # Install HDF5
    install_hdf5
    # Install NetCDF-C
    install_netcdf_c
    # Install NetCDF fortran
    install_netcdf_fortran
    # put installed bin directory in PATH
    export PATH=${INSTALLDIR}/bin:$PATH

}

function icar_install {
    echo icar_install
    cd ${TRAVIS_BUILD_DIR}

    # export NETCDF=/usr
    # export NETCDF=${INSTALLDIR}
    # export FFTW=/usr
    sed -i "s|NETCDF=/usr/local|NETCDF=/usr|" src/makefile
    sed -i "s|FFTW=/usr/local|FFTW=/usr|" src/makefile
    make -C src clean; make -C src -j4 test
    make -C src clean; make -C src -j4 MODE=debugslow
    make -C src clean; make -C src -j4 MODE=debug
    make -C src clean; make -C src -j4 MODE=debugompslow
    make -C src clean; make -C src -j4 MODE=debugomp
    make -C src clean; make -C src -j4 MODE=profile
    make -C src clean; make -C src -j4 MODE=fast
    make -C src clean; make -C src -j4
    echo "icar install succeeded"
}

function icar_script {

    cd ./src
    # ./icar --version
    # ./icar -h
    # ./test_calendar
    # ./test_random
    # ./test_regression
    # ./test_config ../run/downscale_options.txt
    cd ../
    echo "icar script succeeded"
}

function icar_after_success {
  echo icar_after_success
  echo "icar build succeeded"
}

function icar_after_failure {
  echo icar_after_failure
  echo "icar build failed"
}
